name: Rust

on: [push, pull_request]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.78.0
          components: clippy
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/fabulist_core
            packages/fabulist_derive
            packages/fabulist_lang
      - name: Lint `fabulist_core`
        run: cargo clippy -- -D warnings
        working-directory: packages/fabulist_core
      - name: Lint `fabulist_derive`
        run: cargo clippy -- -D warnings
        working-directory: packages/fabulist_derive
      - name: Lint `fabulist_lang`
        run: cargo clippy -- -D warnings
        working-directory: packages/fabulist_lang
  test:
    needs: clippy
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.78.0
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/fabulist_core
            packages/fabulist_derive
            packages/fabulist_lang
      - name: Test `fabulist_core`
        run: cargo test --verbose
        working-directory: packages/fabulist_core
      - name: Test `fabulist_derive`
        run: cargo test --verbose
        working-directory: packages/fabulist_derive
      - name: Test `fabulist_lang`
        run: cargo test --verbose
        working-directory: packages/fabulist_lang
  coverage:
    needs: test
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.78.0
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/fabulist_core
            packages/fabulist_derive
            packages/fabulist_lang
      - name: Generate code coverage for `fabulist_core`
        run: |
          cargo install cargo-tarpaulin 
          cargo tarpaulin --verbose --workspace
        working-directory: packages/fabulist_core
      - name: Generate code coverage for `fabulist_derive`
        run: |
          cargo install cargo-tarpaulin 
          cargo tarpaulin --verbose --workspace
        working-directory: packages/fabulist_derive
      - name: Generate code coverage for `fabulist_lang`
        run: |
          cargo install cargo-tarpaulin 
          cargo tarpaulin --verbose --workspace
        working-directory: packages/fabulist_lang
