name: Rust

on: [push, pull_request]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.78.0
          components: clippy
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/fabulist_core -> ../../target
            packages/fabulist_derive -> ../../target
            packages/fabulist_lang -> ../../target
      - name: Run linter
        run: cargo clippy -- -D warnings
  test:
    needs: clippy
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.78.0
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/fabulist_core -> ../../target
            packages/fabulist_derive -> ../../target
            packages/fabulist_lang -> ../../target
      - name: Run tests
        run: cargo test --verbose
  coverage:
    needs: test
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.78.0
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/fabulist_core -> ../../target
            packages/fabulist_derive -> ../../target
            packages/fabulist_lang -> ../../target
      - name: Generate code coverage
        run: |
          cargo install cargo-tarpaulin 
          cargo tarpaulin --verbose --workspace
