name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/fabulist_core
            packages/fabulist_derive
            packages/fabulist_lang
      - name: Run linter
        run: cargo clippy -- -D warnings
  test:
    needs: clippy
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/fabulist_core
            packages/fabulist_derive
            packages/fabulist_lang
      - name: Run tests
        run: cargo test --verbose
  coverage:
    needs: test
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/fabulist_core
            packages/fabulist_derive
            packages/fabulist_lang
      - name: Generate code coverage
        run: |
          cargo install cargo-tarpaulin 
          cargo tarpaulin --verbose --workspace
